services:
  - type: web
    name: finance-backend
    env: python
    # This tells Render to go into your backend folder
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0